import Header from '@/components/Header/Header'
import '../styles/globals.css'


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className="antialiased">
        <Header />
        <main className="bg-[#f1f5f9]">{ children }</main>
      </body>
    </html>
  )
}
